version: "3.4"

services:
  whisper_api:
    build:
      context: ./whisper-api-batched-inference
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./whisper-api-batched-inference:/app
      - ./whisper-api-batched-inference/models:/models
      - cache-pip:/root/.cache/pip
      - cache-whisper:/root/.cache/whisper
    environment:
      - ASR_MODEL=openai/whisper-large-v3
      - HUGGINGFACE_HUB_CACHE=/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
  cache-faster-whisper:
