services:
  asr:
    image: soar97/triton-whisper:24.09
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - whisper_models:/app/models
    environment:
      - PYTHONIOENCODING=utf-8
      - MODEL_ID=large-v3-turbo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      /bin/bash -c "bash prepare.sh large-v3-turbo"

volumes:
  whisper_models:
